### Este Notebook estara enfocado en el desanidado y normalizacion de los datos de la columna `MISC`. Al terminar continuar con el Notebook 5.

In [1]:
import pandas as pd

In [ ]:
#  Abrimos el dataframe que contiene toda la data de los negocios de google.
g_sitios = pd.read_parquet(r"C:\Users\Juli\Desktop\Data Science\Archivos Proyecto Final\sitios_google_columnas_originales.parquet")

In [27]:
g_sitios

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,Porter Pharmacy,"Porter Pharmacy, 129 N Second St, Cochran, GA ...",0x88f16e41928ff687:0x883dad4fd048e8f8,None,32.388300,-83.357100,[Pharmacy],4.9,16,None,"[[Friday, 8AM–6PM], [Saturday, 8AM–12PM], [Sun...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 6PM,"[0x88f16e41929435cf:0x5b2532a2885e9ef6, 0x88f1...",https://www.google.com/maps/place//data=!4m2!3...
1,City Textile,"City Textile, 3001 E Pico Blvd, Los Angeles, C...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,None,34.018891,-118.215290,[Textile exporter],4.5,6,None,None,None,Open now,"[0x80c2c624136ea88b:0xb0315367ed448771, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
2,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,None,34.058092,-118.292130,[Korean restaurant],4.4,18,None,"[[Thursday, 6:30AM–6PM], [Friday, 6:30AM–6PM],...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 6PM,"[0x80c2c78249aba68f:0x35bf16ce61be751d, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
3,Nova Fabrics,"Nova Fabrics, 2200 E 11th St, Los Angeles, CA ...",0x80c2c89923b27a41:0x32041559418d447,None,34.023669,-118.232930,[Fabric store],3.3,6,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...","{'Accessibility': None, 'Activities': None, 'A...",Open ⋅ Closes 5PM,"[0x80c2c8811477253f:0x23a8a492df1918f7, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
4,Nobel Textile Co,"Nobel Textile Co, 719 E 9th St, Los Angeles, C...",0x80c2c632f933b073:0xc31785961fe826a6,None,34.036694,-118.249421,[Fabric store],4.3,7,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...","{'Accessibility': None, 'Activities': None, 'A...",Open ⋅ Closes 5PM,"[0x80c2c62c496083d1:0xdefa11317fe870a1, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3025006,Steak 48,"Steak 48, 260 S Broad St, Philadelphia, PA 19102",0x89c6c74f43a49b55:0x6be6995921c58b12,None,39.947254,-75.164953,"[Steak house, Fine dining restaurant, Seafood ...",4.6,308,None,"[[Monday, 4–10PM], [Tuesday, 4–10PM], [Wednesd...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 4PM,"[0x89c6c7af1a55f4f9:0x589bb93addf7fd95, 0x89c6...",https://www.google.com/maps/place//data=!4m2!3...
3025007,"Jack Mcnerney Chevrolet, Inc.","Jack Mcnerney Chevrolet, Inc., 363 NY-281, Tul...",0x89da1787d3fdc4a5:0xce92ea6e3cd4d1cc,None,42.788636,-76.122120,[Chevrolet dealer],4.4,143,None,"[[Monday, 8:30AM–7PM], [Tuesday, 8:30AM–7PM], ...","{'Accessibility': None, 'Activities': None, 'A...",Open ⋅ Closes 7PM,"[0x89d98d228469e435:0x3fdc4fa72594151, 0x89d9e...",https://www.google.com/maps/place//data=!4m2!3...
3025008,Central Ny Spay Neuter Assista,"Central Ny Spay Neuter Assista, 17 Salisbury S...",0x89da6b9ce832726f:0xbd0d3630f1e3b42e,None,42.603831,-76.165286,[Veterinarian],4.3,88,None,None,"{'Accessibility': None, 'Activities': None, 'A...",Open now,"[0x89da6c67512700cb:0x69892b3a9a648efe, 0x89d9...",https://www.google.com/maps/place//data=!4m2!3...
3025009,Ok Feed Store,"Ok Feed Store, 16300 SW 296th St, Homestead, F...",0x88d9e872a9e39f3d:0x5de29f50507e5d73,None,25.491641,-80.456076,[Animal feed store],4.9,13,None,"[[Monday, 9AM–6PM], [Tuesday, 9AM–6PM], [Wedne...","{'Accessibility': None, 'Activities': None, 'A...",Open ⋅ Closes 6PM,"[0x88d9e86cb955da7b:0xeda838b28926c524, 0x88d9...",https://www.google.com/maps/place//data=!4m2!3...
3025010,Crestview Crossing,"Crestview Crossing, Newberg, OR 97132",0x54956b3944b1654d:0x7797cead9a485c22,None,45.310254,-122.935500,[Lodging],5.0,1,None,None,{'Accessibility': ['Wheelchair accessible entr...,None,None,https://www.google.com/maps/place//data=!4m2!3...

In [28]:
# Creamos una nueva tabla misc
misc_sitios = g_sitios[['gmap_id', 'MISC']]

# Donde MISC sea NULO no hay Información Se pueden Borrar ya que esta tabla es SOLO MISCELANEOS.
misc_sitios = misc_sitios.dropna(subset=['MISC'])

In [30]:
# Se Define una Función que convierte los Diccionarios en Listas para poder Aplicar `explode` despues.  Sólo se toman aquellos pares del diccionario donde value is not None
def dict_to_list(diccionario:dict) -> list:
    """ Devuelve el Diccionario de la columna `MISC` y lo retorna
                    como una lista de String "key:Value" Siempre y cuando el 
                    value de la pareja no sea Nulo.

    Args:
        diccionario (dict): diccionario recibido

    Returns:
        list: Lista a devolver
    """
    return [f"{key}: {value}" for key, value in diccionario.items() if value is not None]

In [31]:
# Aplicamos la funcion definida arriba.
misc_sitios['lista_misc'] = misc_sitios['MISC'].apply(dict_to_list)

# Muestra parcial de la tabla:
misc_sitios.head()

,gmap_id,MISC,lista_misc
0,0x88f16e41928ff687:0x883dad4fd048e8f8,{'Accessibility': ['Wheelchair accessible entr...,[Accessibility: ['Wheelchair accessible entran...
2,0x80c2c778e3b73d33:0xbdc58662a4a97d49,{'Accessibility': ['Wheelchair accessible entr...,[Accessibility: ['Wheelchair accessible entran...
3,0x80c2c89923b27a41:0x32041559418d447,"{'Accessibility': None, 'Activities': None, 'A...",[Payments: ['Checks' 'Debit cards' 'Credit car...
4,0x80c2c632f933b073:0xc31785961fe826a6,"{'Accessibility': None, 'Activities': None, 'A...",[Service options: ['In-store pickup']]
5,0x80c2cf163db6bc89:0x219484e2edbcfa41,{'Accessibility': ['Wheelchair accessible entr...,[Accessibility: ['Wheelchair accessible entran...

Se borra la columna MISC, se aplica explode al dataframe con respecto a la columna `lista_misc` y luego renombrar la columna para tener lista la tabla

In [32]:
misc_sitios = misc_sitios.drop(columns=['MISC'])

misc_sitios = misc_sitios.explode('lista_misc')

misc_sitios.rename(columns={'lista_misc': 'misc'}, inplace=True)
misc_sitios.head()

,gmap_id,misc
0,0x88f16e41928ff687:0x883dad4fd048e8f8,Accessibility: ['Wheelchair accessible entrance']
0,0x88f16e41928ff687:0x883dad4fd048e8f8,Health & safety: ['Mask required' 'Staff requi...
0,0x88f16e41928ff687:0x883dad4fd048e8f8,Planning: ['Quick visit']
0,0x88f16e41928ff687:0x883dad4fd048e8f8,Service options: ['In-store shopping' 'Same-da...
2,0x80c2c778e3b73d33:0xbdc58662a4a97d49,Accessibility: ['Wheelchair accessible entrance']

In [34]:
# Guaradamos la tabla desanidada que se conecta a travez de gmap_id con la tabla principal.
misc_sitios.to_parquet(r"C:\Users\Juli\Desktop\Data Science\Archivos Proyecto Final\google_misc_sitios.parquet")

Filtrare la tabla con los estados y categorías seleccionadas para este proyecto. Para ello, importaré el dataframe "vi.g_sitios". Realizaré una unión entre ambos dataframes para luego filtrar por las categorías y estados elegidos.

In [35]:
sitios = pd.read_parquet(r"C:\Users\Juli\Desktop\Data Science\Archivos Proyecto Final\v1.g_sitios.parquet")
sitios.head()

,name,gmap_id,avg_rating,num_of_reviews,url,monday,tuesday,wednesday,thursday,friday,saturday,sunday,category_general_id,id_estado
0,Oneyda's Bakery,0x88dae191ee505917:0x6ba3e25388d3fad4,4.6,19,https://www.google.com/maps/place//data=!4m2!3...,8AM–6PM,8AM–6PM,8AM–6PM,8AM–6PM,8AM–6PM,8AM–6PM,Closed,4,7
1,TACOS LA CABANA,0x808f879f35b5088b:0xe3541cec7a95bd88,5.0,2,https://www.google.com/maps/place//data=!4m2!3...,5–11PM,Closed,Closed,Closed,5–11PM,5–11PM,5–11PM,3,9
2,Tropical Park Liquors,0x88d9b99475d9fd7b:0xea6083d207b2471a,4.7,8,https://www.google.com/maps/place//data=!4m2!3...,10AM–10PM,10AM–10PM,10AM–12AM,10AM–12AM,10AM–12AM,10AM–12AM,10AM–10PM,4,7
3,The Nutrition Group,0x89c88de475520cc7:0xeff46469445b5212,3.2,17,https://www.google.com/maps/place//data=!4m2!3...,9AM–8PM,9AM–8PM,9AM–8PM,9AM–8PM,9AM–8PM,9AM–5PM,Closed,4,13
4,Top Cat Seafood Restaurant,0x864e9891e381f3df:0x4cefe6219bc9199c,3.9,8,https://www.google.com/maps/place//data=!4m2!3...,12–8PM,12–8PM,12–8PM,12–8PM,12–8PM,12–8PM,12–8PM,3,18

In [36]:
df_merged = pd.merge(misc_sitios, sitios[['gmap_id']], on='gmap_id', how='inner')
df_merged

,gmap_id,misc
0,0x88dae191ee505917:0x6ba3e25388d3fad4,Service options: ['Delivery']
1,0x808f879f35b5088b:0xe3541cec7a95bd88,Amenities: ['Good for kids']
2,0x808f879f35b5088b:0xe3541cec7a95bd88,Atmosphere: ['Casual']
3,0x808f879f35b5088b:0xe3541cec7a95bd88,Crowd: ['Groups']
4,0x808f879f35b5088b:0xe3541cec7a95bd88,Offerings: ['Comfort food' 'Quick bite']
...,...,...
653945,0x89c6c74f43a49b55:0x6be6995921c58b12,Offerings: ['Alcohol' 'Beer' 'Cocktails' 'Coff...
653946,0x89c6c74f43a49b55:0x6be6995921c58b12,Payments: ['Debit cards']
653947,0x89c6c74f43a49b55:0x6be6995921c58b12,Planning: ['Dinner reservations recommended' '...
653948,0x89c6c74f43a49b55:0x6be6995921c58b12,Popular for: ['Dinner' 'Solo dining']
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options: ['Takeout' 'Dine-in' 'Delivery']

In [39]:
pd.set_option('display.max_colwidth', None)
df_merged

,gmap_id,misc
0,0x88dae191ee505917:0x6ba3e25388d3fad4,Service options: ['Delivery']
1,0x808f879f35b5088b:0xe3541cec7a95bd88,Amenities: ['Good for kids']
2,0x808f879f35b5088b:0xe3541cec7a95bd88,Atmosphere: ['Casual']
3,0x808f879f35b5088b:0xe3541cec7a95bd88,Crowd: ['Groups']
4,0x808f879f35b5088b:0xe3541cec7a95bd88,Offerings: ['Comfort food' 'Quick bite']
...,...,...
653945,0x89c6c74f43a49b55:0x6be6995921c58b12,Offerings: ['Alcohol' 'Beer' 'Cocktails' 'Coffee' 'Comfort food' 'Happy hour drinks'\n 'Hard liquor' 'Late-night food' 'Wine']
653946,0x89c6c74f43a49b55:0x6be6995921c58b12,Payments: ['Debit cards']
653947,0x89c6c74f43a49b55:0x6be6995921c58b12,Planning: ['Dinner reservations recommended' 'Accepts reservations']
653948,0x89c6c74f43a49b55:0x6be6995921c58b12,Popular for: ['Dinner' 'Solo dining']
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options: ['Takeout' 'Dine-in' 'Delivery']

In [40]:
# Extraer el texto antes del primer ':'
df_merged['category'] = df_merged['misc'].str.split(':').str[0]

# Obtener las categorías únicas
unique_categories = df_merged['category'].unique()
df_merged

,gmap_id,misc,category
0,0x88dae191ee505917:0x6ba3e25388d3fad4,Service options: ['Delivery'],Service options
1,0x808f879f35b5088b:0xe3541cec7a95bd88,Amenities: ['Good for kids'],Amenities
2,0x808f879f35b5088b:0xe3541cec7a95bd88,Atmosphere: ['Casual'],Atmosphere
3,0x808f879f35b5088b:0xe3541cec7a95bd88,Crowd: ['Groups'],Crowd
4,0x808f879f35b5088b:0xe3541cec7a95bd88,Offerings: ['Comfort food' 'Quick bite'],Offerings
...,...,...,...
653945,0x89c6c74f43a49b55:0x6be6995921c58b12,Offerings: ['Alcohol' 'Beer' 'Cocktails' 'Coffee' 'Comfort food' 'Happy hour drinks'\n 'Hard liquor' 'Late-night food' 'Wine'],Offerings
653946,0x89c6c74f43a49b55:0x6be6995921c58b12,Payments: ['Debit cards'],Payments
653947,0x89c6c74f43a49b55:0x6be6995921c58b12,Planning: ['Dinner reservations recommended' 'Accepts reservations'],Planning
653948,0x89c6c74f43a49b55:0x6be6995921c58b12,Popular for: ['Dinner' 'Solo dining'],Popular for
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options: ['Takeout' 'Dine-in' 'Delivery'],Service options

In [42]:
# Extraer el contenido después de ':' en la columna 'misc'
df_merged['misc_content'] = df_merged['misc'].str.split(':').str[1].str.strip()
# Usar una expresión regular para extraer cada texto dentro de comillas simples
df_merged['misc_content'] = df_merged['misc'].str.extractall(r"'(.*?)'").groupby(level=0).agg(list)
# Separar la lista en filas
df_merged = df_merged.explode('misc_content')
# Muestra de la tabla
df_merged = df_merged[['gmap_id', 'category', 'misc_content']]

In [43]:
df_merged.rename(columns={'category': 'categoria_atributo'}, inplace=True)
df_merged.rename(columns={'misc_content': 'atributo'}, inplace=True)
df_merged.rename(columns={'gmap_id': 'id_negocio'}, inplace=True)
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19887362 entries, 0 to 653949
Data columns (total 3 columns):
 #   Column              Dtype
---  ------              -----
 0   id_negocio          object
 1   categoria_atributo  object
 2   atributo            object
dtypes: object(3)
memory usage: 606.9+ MB

In [44]:
df_merged

,id_negocio,categoria_atributo,atributo
0,0x88dae191ee505917:0x6ba3e25388d3fad4,Service options,Delivery
1,0x808f879f35b5088b:0xe3541cec7a95bd88,Amenities,Good for kids
2,0x808f879f35b5088b:0xe3541cec7a95bd88,Atmosphere,Casual
3,0x808f879f35b5088b:0xe3541cec7a95bd88,Crowd,Groups
4,0x808f879f35b5088b:0xe3541cec7a95bd88,Offerings,Comfort food
...,...,...,...
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Dine-in
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Delivery
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Takeout
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Dine-in
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Delivery

Conteo de nulos

In [45]:
nulos_por_columna = df_merged.isnull().sum()
nulos_por_columna

id_negocio              0
categoria_atributo      0
atributo              522
dtype: int64

In [46]:
# Eliminar filas nulas
df_merged = df_merged[df_merged['atributo'].notnull()]
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19886840 entries, 0 to 653949
Data columns (total 3 columns):
 #   Column              Dtype
---  ------              -----
 0   id_negocio          object
 1   categoria_atributo  object
 2   atributo            object
dtypes: object(3)
memory usage: 606.9+ MB

Veamos cuantas categorias de atributos hay

In [48]:
categorias = df_merged['categoria_atributo'].unique()
print(categorias,'\ntotal categorias:',len(categorias))

['Service options' 'Amenities' 'Atmosphere' 'Crowd' 'Offerings'
 'Popular for' 'Accessibility' 'Planning' 'Health & safety'
 'Dining options' 'Highlights' 'Payments' 'From the business' 'Recycling'
 'Health and safety']
total categorias: 15

### Existe una categoria duplicada de distinto nombre: 
- `Health & safety`
- `Health and safety`
La agrupamos en una sola.

In [50]:
df_merged.loc[:, 'categoria_atributo'] = df_merged['categoria_atributo'].replace({'Health & safety': 'Health and safety'})

veamos si hay relaciones en otras categorias para agruparlas

In [54]:
categorias = df_merged['categoria_atributo'].unique()

# Iterar a través de cada categoría y mostrar los atributos únicos
for categoria in categorias:
    atributos = df_merged[df_merged['categoria_atributo'] == categoria]['atributo'].unique()
    print(f"{categoria}\n", atributos, "\n")

Service options
 ['Delivery' 'Takeout' 'Dine-in' 'In-store shopping' 'Curbside pickup'
 'In-store pickup' 'Same-day delivery' 'Drive-through' 'Outdoor seating'
 'No-contact delivery' 'Onsite services' 'Online appointments'
 'Online care' 'Outdoor services' 'Online classes' 'Language assistance'
 'Online estimates' 'Takeaway' 'In-store pick-up']

Amenities
 ['Good for kids' 'Wi-Fi' 'Restroom' 'Bar onsite' 'High chairs'
 'Gender-neutral restroom' 'Public restroom' 'Restaurant' 'Swimming pool'
 'Mechanic' 'Child care' 'Toilets' 'Bar on site' 'Gender-neutral toilets'
 'Public toilet' 'Golf course' 'Stadium seating']

Atmosphere
 ['Casual' 'Cozy' 'Quiet' 'Romantic' 'Upscale' 'Historic' 'Trending' 'Cosy'
 'Upmarket' 'Lively']

Crowd
 ['Groups' 'Family-friendly' 'Tourists' 'College students' 'Locals'
 'Family friendly' 'University students']

Offerings
 ['Comfort food' 'Quick bite' 'Coffee' 'Happy hour drinks'
 'Late-night food' 'Alcohol' 'Beer' 'Cocktails' 'Dancing' 'Hard liquor'
 'Wine' 'Food' 'Food at bar' ' menu" ' ' ' 'Small plates'
 'Healthy options' 'Vegetarian options' 'Happy hour food' 'Organic dishes'
 'Prepared foods' 'All you can eat' 'Halal food' 'Salad bar'
 'Check cashing' 'Organic products' 'Passport photos' 'Braille menu'
 'Buys used goods' 'Full service gas' 'Assembly service' 'Repair services'
 'Service guarantee' 'Ethanol-free gas' 's clothing" "Men'
 's clothing" "Women' 'Car wash' 'Oil change' 'Used goods'
 'Happy-hour food' 'Happy-hour drinks' 'Spirits' 'Cheque cashing'
 'Ethanol-free petrol']

Popular for
 ['Dinner' 'Solo dining' 'Lunch' 'Breakfast' 'Good for working on laptop']

Accessibility
 ['Wheelchair accessible entrance' 'Wheelchair accessible parking lot'
 'Wheelchair accessible restroom' 'Wheelchair accessible seating'
 'Wheelchair accessible elevator' 'Wheelchair-accessible entrance'
 'Wheelchair-accessible seating' 'Wheelchair-accessible toilet'
 'Wheelchair-accessible car park' 'Wheelchair-accessible lift'
 'Assisted listening devices' 'Wheelchair rental']

Planning
 ['Quick visit' 'Accepts reservations' 'Membership required'
 'Dinner reservations recommended' 'Usually a wait'
 'Appointments recommended' 'Brunch reservations recommended'
 'Lunch reservations recommended']

Health and safety
 ['Mask required' 'Staff wear masks' 'Staff get temperature checks'
 'Staff required to disinfect surfaces between visits'
 'Safety dividers at checkout' 'Reservations required'
 'Temperature check required' 'Appointment required']

Dining options
 ['Breakfast' 'Lunch' 'Dessert' 'Seating' 'Dinner' 'Catering'
 'Counter service' 'Outside food allowed' 'Pay ahead']

Highlights
 ['Fast service' 'Great coffee' 'Great beer selection' 'Great cocktails'
 'Great wine list' 'Live music' 'Great tea selection' 'Great bar food'
 'Sports' 'Great dessert' 'Great produce' 'Fireplace' 'LGBTQ friendly'
 'Transgender safespace' 'Bar games' 'Karaoke' 'Live performances'
 'Trivia night' 'Active military discounts' 'Serves local specialty'
 'Rooftop seating' 'Play area' 'LGBTQ-friendly' 'Transgender safe space'
 'Sport' 'Quiz night' '3D movies' 'Good discounts']

Payments
 ['Debit cards' 'NFC mobile payments' 'Credit cards' 'Checks' 'Cash-only'
 'Cash only' 'Cheques']

From the business
 ['Identifies as women-led' 'Identifies as veteran-led'
 'Identifies as Black-owned']

Recycling
 ['Plastic bags' 'Glass bottles' 'Metal cans' 'Plastic bottles']

### Viendo los atributos comprendemos que Health and Safety es un atributo de la pandemia el cual hoy ya no es necesario ni tenido en cuenta para lugares turisticos. Por ende vamos a eliminar ese atributo.

In [55]:
# Quitamos Health and Safety de los atributos.
df_merged = df_merged[df_merged['categoria_atributo'] != 'Health and safety']
# Comprobamos
categorias = df_merged['categoria_atributo'].unique()
print(categorias)

['Service options' 'Amenities' 'Atmosphere' 'Crowd' 'Offerings'
 'Popular for' 'Accessibility' 'Planning' 'Dining options' 'Highlights'
 'Payments' 'From the business' 'Recycling']

### Tambien vemos muchos atributos repetidos. Algunos contienen - y otros solo espacios. Asi que reemplazamos - por espacios y ver de nuevo las categorias

Ademas generalizar todos los tipos de inclusion sexual en una sola categoria. 'LGBTQ Friendly'

In [ ]:
# Quitar el guion en los valores de 'atributo'
df_merged.loc[:, 'atributo'] = df_merged['atributo'].str.replace('-', ' ', regex=False)

# Generalizar el atributo.
mapeo_lgbtq = {
    'LGBTQ friendly': 'LGBTQ friendly',
    'LGBTQ-friendly': 'LGBTQ friendly',
    'Transgender safespace': 'LGBTQ friendly',
    'Transgender safe space': 'LGBTQ friendly'
}

mapeo_accesibilidad = {
    'Wheelchair accessible restroom': 'Wheelchair accessible toilet',
    'Wheelchair accessible parking lot': 'Wheelchair accessible car park',
    'Wheelchair accessible lift': 'Wheelchair accessible elevator'
}

# Aplicar el mapeo a la columna 'atributo'
df_merged.loc[:, 'atributo'] = df_merged['atributo'].replace(mapeo_lgbtq)
df_merged.loc[:, 'atributo'] = df_merged['atributo'].replace(mapeo_accesibilidad)

Volvamos a ver los atributos

In [58]:
categorias = df_merged['categoria_atributo'].unique()

# Iterar a través de cada categoría y mostrar los atributos únicos
for categoria in categorias:
    atributos = df_merged[df_merged['categoria_atributo'] == categoria]['atributo'].unique()
    print(f"{categoria}\n", atributos, "\n")

Service options
 ['Delivery' 'Takeout' 'Dine in' 'In store shopping' 'Curbside pickup'
 'In store pickup' 'Same day delivery' 'Drive through' 'Outdoor seating'
 'No contact delivery' 'Onsite services' 'Online appointments'
 'Online care' 'Outdoor services' 'Online classes' 'Language assistance'
 'Online estimates' 'Takeaway' 'In store pick up']

Amenities
 ['Good for kids' 'Wi Fi' 'Restroom' 'Bar onsite' 'High chairs'
 'Gender neutral restroom' 'Public restroom' 'Restaurant' 'Swimming pool'
 'Mechanic' 'Child care' 'Toilets' 'Bar on site' 'Gender neutral toilets'
 'Public toilet' 'Golf course' 'Stadium seating']

Atmosphere
 ['Casual' 'Cozy' 'Quiet' 'Romantic' 'Upscale' 'Historic' 'Trending' 'Cosy'
 'Upmarket' 'Lively']

Crowd
 ['Groups' 'Family friendly' 'Tourists' 'College students' 'Locals'
 'University students']

Offerings
 ['Comfort food' 'Quick bite' 'Coffee' 'Happy hour drinks'
 'Late night food' 'Alcohol' 'Beer' 'Cocktails' 'Dancing' 'Hard liquor'
 'Wine' 'Food' 'Food at bar' ' menu" ' ' ' 'Small plates'
 'Healthy options' 'Vegetarian options' 'Happy hour food' 'Organic dishes'
 'Prepared foods' 'All you can eat' 'Halal food' 'Salad bar'
 'Check cashing' 'Organic products' 'Passport photos' 'Braille menu'
 'Buys used goods' 'Full service gas' 'Assembly service' 'Repair services'
 'Service guarantee' 'Ethanol free gas' 's clothing" "Men'
 's clothing" "Women' 'Car wash' 'Oil change' 'Used goods' 'Spirits'
 'Cheque cashing' 'Ethanol free petrol']

Popular for
 ['Dinner' 'Solo dining' 'Lunch' 'Breakfast' 'Good for working on laptop']

Accessibility
 ['Wheelchair accessible entrance' 'Wheelchair accessible car park'
 'Wheelchair accessible toilet' 'Wheelchair accessible seating'
 'Wheelchair accessible elevator' 'Assisted listening devices'
 'Wheelchair rental']

Planning
 ['Quick visit' 'Accepts reservations' 'Membership required'
 'Dinner reservations recommended' 'Usually a wait'
 'Appointments recommended' 'Brunch reservations recommended'
 'Lunch reservations recommended']

Dining options
 ['Breakfast' 'Lunch' 'Dessert' 'Seating' 'Dinner' 'Catering'
 'Counter service' 'Outside food allowed' 'Pay ahead']

Highlights
 ['Fast service' 'Great coffee' 'Great beer selection' 'Great cocktails'
 'Great wine list' 'Live music' 'Great tea selection' 'Great bar food'
 'Sports' 'Great dessert' 'Great produce' 'Fireplace' 'LGBTQ friendly'
 'Bar games' 'Karaoke' 'Live performances' 'Trivia night'
 'Active military discounts' 'Serves local specialty' 'Rooftop seating'
 'Play area' 'Sport' 'Quiz night' '3D movies' 'Good discounts']

Payments
 ['Debit cards' 'NFC mobile payments' 'Credit cards' 'Checks' 'Cash only'
 'Cheques']

From the business
 ['Identifies as women led' 'Identifies as veteran led'
 'Identifies as Black owned']

Recycling
 ['Plastic bags' 'Glass bottles' 'Metal cans' 'Plastic bottles']

Vemos que dentro de offering se encuentra un atributo 'braille menu' esto es muy importante para determinar la accesibilidad asi que lo agruparemos en esa categoria. Ademas el atributo 'High chairs' tambien podria entrar dentro de la accesibilidad para problemas de altura.

In [59]:
# Cambiar la categoría a "Accessibility" para registros con "Offerings" y "Braille menu"
df_merged.loc[(df_merged['categoria_atributo'] == 'Offerings') & (df_merged['atributo'] == 'Braille menu'), 'categoria_atributo'] = 'Accessibility'
df_merged.loc[(df_merged['categoria_atributo'] == 'Amenities') & (df_merged['atributo'] == 'High chairs'), 'categoria_atributo'] = 'Accessibility'

In [60]:
# Muestra final
categorias = df_merged['categoria_atributo'].unique()

# Iterar a través de cada categoría y mostrar los atributos únicos
for categoria in categorias:
    atributos = df_merged[df_merged['categoria_atributo'] == categoria]['atributo'].unique()
    print(f"{categoria}\n", atributos, "\n")

Service options
 ['Delivery' 'Takeout' 'Dine in' 'In store shopping' 'Curbside pickup'
 'In store pickup' 'Same day delivery' 'Drive through' 'Outdoor seating'
 'No contact delivery' 'Onsite services' 'Online appointments'
 'Online care' 'Outdoor services' 'Online classes' 'Language assistance'
 'Online estimates' 'Takeaway' 'In store pick up']

Amenities
 ['Good for kids' 'Wi Fi' 'Restroom' 'Bar onsite' 'Gender neutral restroom'
 'Public restroom' 'Restaurant' 'Swimming pool' 'Mechanic' 'Child care'
 'Toilets' 'Bar on site' 'Gender neutral toilets' 'Public toilet'
 'Golf course' 'Stadium seating']

Atmosphere
 ['Casual' 'Cozy' 'Quiet' 'Romantic' 'Upscale' 'Historic' 'Trending' 'Cosy'
 'Upmarket' 'Lively']

Crowd
 ['Groups' 'Family friendly' 'Tourists' 'College students' 'Locals'
 'University students']

Offerings
 ['Comfort food' 'Quick bite' 'Coffee' 'Happy hour drinks'
 'Late night food' 'Alcohol' 'Beer' 'Cocktails' 'Dancing' 'Hard liquor'
 'Wine' 'Food' 'Food at bar' ' menu" ' ' ' 'Small plates'
 'Healthy options' 'Vegetarian options' 'Happy hour food' 'Organic dishes'
 'Prepared foods' 'All you can eat' 'Halal food' 'Salad bar'
 'Check cashing' 'Organic products' 'Passport photos' 'Buys used goods'
 'Full service gas' 'Assembly service' 'Repair services'
 'Service guarantee' 'Ethanol free gas' 's clothing" "Men'
 's clothing" "Women' 'Car wash' 'Oil change' 'Used goods' 'Spirits'
 'Cheque cashing' 'Ethanol free petrol']

Popular for
 ['Dinner' 'Solo dining' 'Lunch' 'Breakfast' 'Good for working on laptop']

Accessibility
 ['Wheelchair accessible entrance' 'Wheelchair accessible car park'
 'Wheelchair accessible toilet' 'Wheelchair accessible seating'
 'High chairs' 'Wheelchair accessible elevator' 'Braille menu'
 'Assisted listening devices' 'Wheelchair rental']

Planning
 ['Quick visit' 'Accepts reservations' 'Membership required'
 'Dinner reservations recommended' 'Usually a wait'
 'Appointments recommended' 'Brunch reservations recommended'
 'Lunch reservations recommended']

Dining options
 ['Breakfast' 'Lunch' 'Dessert' 'Seating' 'Dinner' 'Catering'
 'Counter service' 'Outside food allowed' 'Pay ahead']

Highlights
 ['Fast service' 'Great coffee' 'Great beer selection' 'Great cocktails'
 'Great wine list' 'Live music' 'Great tea selection' 'Great bar food'
 'Sports' 'Great dessert' 'Great produce' 'Fireplace' 'LGBTQ friendly'
 'Bar games' 'Karaoke' 'Live performances' 'Trivia night'
 'Active military discounts' 'Serves local specialty' 'Rooftop seating'
 'Play area' 'Sport' 'Quiz night' '3D movies' 'Good discounts']

Payments
 ['Debit cards' 'NFC mobile payments' 'Credit cards' 'Checks' 'Cash only'
 'Cheques']

From the business
 ['Identifies as women led' 'Identifies as veteran led'
 'Identifies as Black owned']

Recycling
 ['Plastic bags' 'Glass bottles' 'Metal cans' 'Plastic bottles']

Como paso final, almacenaré la tabla en un archivo parquet para su posterior carga a la base de datos.

In [61]:
df_merged.to_parquet(r"C:\Users\Juli\Desktop\Data Science\Archivos Proyecto Final\v0_misc.parquet")

In [62]:
# Muestra de la tabla final
df_merged

,id_negocio,categoria_atributo,atributo
0,0x88dae191ee505917:0x6ba3e25388d3fad4,Service options,Delivery
1,0x808f879f35b5088b:0xe3541cec7a95bd88,Amenities,Good for kids
2,0x808f879f35b5088b:0xe3541cec7a95bd88,Atmosphere,Casual
3,0x808f879f35b5088b:0xe3541cec7a95bd88,Crowd,Groups
4,0x808f879f35b5088b:0xe3541cec7a95bd88,Offerings,Comfort food
...,...,...,...
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Dine in
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Delivery
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Takeout
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Dine in
653949,0x89c6c74f43a49b55:0x6be6995921c58b12,Service options,Delivery

In [2]:
misc['id_misc'] = range(1, len(misc) + 1)

In [1]:
import pandas as pd 
misc = pd.read_parquet(r"C:\Users\mauri\OneDrive\Escritorio\proyectogrupal\data\v0_misc.parquet", engine='pyarrow')
misc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19331265 entries, 0 to 653949
Data columns (total 4 columns):
 #   Column              Dtype
---  ------              -----
 0   id_negocio          object
 1   categoria_atributo  object
 2   atributo            object
 3   id_misc             int64
dtypes: int64(1), object(3)
memory usage: 737.4+ MB

In [7]:
# Lista de categorías que deseas excluir
categorias_excluir = ['Recycling', 'From the business','Payments','Dining options', 'Planning', 'Service options','Offerings']
atributos_excluir = ['Fireplace','Active military discounts','Quiz night', '3D movies','Swimming pool', 'Mechanic','Golf course', 'Stadium seating']

# Filtrar el DataFrame para quedarte solo con las filas que NO tengan esas categorías
filtrado = misc[~misc['categoria_atributo'].isin(categorias_excluir)]
filtrado = filtrado[~filtrado['atributo'].isin(atributos_excluir)]
filtrado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3869273 entries, 1 to 653948
Data columns (total 4 columns):
 #   Column              Dtype
---  ------              -----
 0   id_negocio          object
 1   categoria_atributo  object
 2   atributo            object
 3   id_misc             int64
dtypes: int64(1), object(3)
memory usage: 147.6+ MB

In [8]:
# Muestra final
categorias = filtrado['categoria_atributo'].unique()

# Iterar a través de cada categoría y mostrar los atributos únicos
for categoria in categorias:
    atributos = filtrado[filtrado['categoria_atributo'] == categoria]['atributo'].unique()
    print(f"{categoria}\n", atributos, "\n")

Amenities
 ['Good for kids' 'Wi Fi' 'Restroom' 'Bar onsite' 'Gender neutral restroom'
 'Public restroom' 'Restaurant' 'Child care' 'Toilets' 'Bar on site'
 'Gender neutral toilets' 'Public toilet']

Atmosphere
 ['Casual' 'Cozy' 'Quiet' 'Romantic' 'Upscale' 'Historic' 'Trending' 'Cosy'
 'Upmarket' 'Lively']

Crowd
 ['Groups' 'Family friendly' 'Tourists' 'College students' 'Locals'
 'University students']

Popular for
 ['Dinner' 'Solo dining' 'Lunch' 'Breakfast' 'Good for working on laptop']

Accessibility
 ['Wheelchair accessible entrance' 'Wheelchair accessible car park'
 'Wheelchair accessible toilet' 'Wheelchair accessible seating'
 'High chairs' 'Wheelchair accessible elevator' 'Braille menu'
 'Assisted listening devices' 'Wheelchair rental']

Highlights
 ['Fast service' 'Great coffee' 'Great beer selection' 'Great cocktails'
 'Great wine list' 'Live music' 'Great tea selection' 'Great bar food'
 'Sports' 'Great dessert' 'Great produce' 'LGBTQ friendly' 'Bar games'
 'Karaoke' 'Live performances' 'Trivia night' 'Serves local specialty'
 'Rooftop seating' 'Play area' 'Sport' 'Good discounts']

In [9]:
filtrado.to_parquet("v1_misc.parquet")